global using BuildingBlocks.Application.CQRS;
global using BuildingBlocks.Application.Events;
global using BuildingBlocks.Application.Results;
global using BuildingBlocks.Application.Abstractions;
global using Nutrition.Domain.Repositories;
global using FluentValidation;
global using MediatR;
global using Microsoft.AspNetCore.Builder;
global using Nutrition.Application.Errors;
