// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nutrition.Infrastructure.Persistence;

#nullable disable

namespace Nutrition.Infrastructure.Migrations
{
    [DbContext(typeof(NutritionDbContext))]
    [Migration("20260414190622_InitNutritionModule")]
    partial class InitNutritionModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("IsProcessed", "OccurredOnUtc")
                        .HasFilter("[IsProcessed] = 0");

                    b.ToTable("OutboxMessages", "outbox");
                });

            modelBuilder.Entity("Nutrition.Domain.Entity.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DefaultServingSize")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Fiber")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ServingUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Foods", "nutrition");
                });

            modelBuilder.Entity("Nutrition.Domain.Entity.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MealPlans", "nutrition");
                });

            modelBuilder.Entity("Nutrition.Domain.Entity.Food", b =>
                {
                    b.OwnsOne("Nutrition.Domain.ValueObjects.MacroNutrients", "Macros", b1 =>
                        {
                            b1.Property<Guid>("FoodId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("Calories");

                            b1.Property<decimal>("Carbohydrates")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("Carbohydrates");

                            b1.Property<decimal>("Fat")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("Fat");

                            b1.Property<decimal>("Protein")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("Protein");

                            b1.HasKey("FoodId");

                            b1.ToTable("Foods", "nutrition");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.Navigation("Macros")
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Domain.Entity.MealPlan", b =>
                {
                    b.OwnsMany("Nutrition.Domain.Entity.Meal", "Meals", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<Guid>("MealPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<int>("Order")
                                .HasColumnType("int");

                            b1.Property<byte[]>("RowVersion")
                                .HasColumnType("varbinary(max)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("MealPlanId");

                            b1.ToTable("Meals", "nutrition");

                            b1.WithOwner()
                                .HasForeignKey("MealPlanId");

                            b1.OwnsMany("Nutrition.Domain.Entity.MealItem", "MealItems", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CreatedBy")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<DateTime>("CreatedDate")
                                        .HasColumnType("datetime2");

                                    b2.Property<Guid>("FoodId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("FoodName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<bool>("IsActive")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("IsDeleted")
                                        .HasColumnType("bit");

                                    b2.Property<Guid>("MealId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Quantity")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)");

                                    b2.Property<byte[]>("RowVersion")
                                        .HasColumnType("varbinary(max)");

                                    b2.Property<string>("ServingUnit")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("UpdatedBy")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<DateTime?>("UpdatedDate")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MealId");

                                    b2.ToTable("MealItems", "nutrition");

                                    b2.WithOwner()
                                        .HasForeignKey("MealId");

                                    b2.OwnsOne("Nutrition.Domain.ValueObjects.MacroNutrients", "Macros", b3 =>
                                        {
                                            b3.Property<Guid>("MealItemId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<decimal>("Calories")
                                                .HasPrecision(10, 2)
                                                .HasColumnType("decimal(10,2)")
                                                .HasColumnName("Calories");

                                            b3.Property<decimal>("Carbohydrates")
                                                .HasPrecision(10, 2)
                                                .HasColumnType("decimal(10,2)")
                                                .HasColumnName("Carbohydrates");

                                            b3.Property<decimal>("Fat")
                                                .HasPrecision(10, 2)
                                                .HasColumnType("decimal(10,2)")
                                                .HasColumnName("Fat");

                                            b3.Property<decimal>("Protein")
                                                .HasPrecision(10, 2)
                                                .HasColumnType("decimal(10,2)")
                                                .HasColumnName("Protein");

                                            b3.HasKey("MealItemId");

                                            b3.ToTable("MealItems", "nutrition");

                                            b3.WithOwner()
                                                .HasForeignKey("MealItemId");
                                        });

                                    b2.Navigation("Macros")
                                        .IsRequired();
                                });

                            b1.Navigation("MealItems");
                        });

                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
