// <auto-generated />
using System;
using BodyMetrics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BodyMetrics.Infrastructure.Migrations
{
    [DbContext(typeof(BodyMetricsDbContext))]
    [Migration("20260423152023_AddShoulderCircumference")]
    partial class AddShoulderCircumference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BodyMetrics.Domain.Entity.BodyMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ArmCircumference")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("ChestCircumference")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HipCircumference")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MuscleMass")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NeckCircumference")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("ShoulderCircumference")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("ThighCircumference")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("WaistCircumference")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BodyMetrics", "bodymetrics");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("IsProcessed", "OccurredOnUtc")
                        .HasFilter("[IsProcessed] = 0");

                    b.ToTable("OutboxMessages", "outbox");
                });

            modelBuilder.Entity("BodyMetrics.Domain.Entity.BodyMetric", b =>
                {
                    b.OwnsOne("BodyMetrics.Domain.ValueObjects.BodyHeight", "Height", b1 =>
                        {
                            b1.Property<Guid>("BodyMetricId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("Height");

                            b1.HasKey("BodyMetricId");

                            b1.ToTable("BodyMetrics", "bodymetrics");

                            b1.WithOwner()
                                .HasForeignKey("BodyMetricId");
                        });

                    b.OwnsOne("BodyMetrics.Domain.ValueObjects.BodyWeight", "Weight", b1 =>
                        {
                            b1.Property<Guid>("BodyMetricId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("Weight");

                            b1.HasKey("BodyMetricId");

                            b1.ToTable("BodyMetrics", "bodymetrics");

                            b1.WithOwner()
                                .HasForeignKey("BodyMetricId");
                        });

                    b.OwnsOne("BodyMetrics.Domain.ValueObjects.Percentage", "BodyFatPercentage", b1 =>
                        {
                            b1.Property<Guid>("BodyMetricId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("BodyFatPercentage");

                            b1.HasKey("BodyMetricId");

                            b1.ToTable("BodyMetrics", "bodymetrics");

                            b1.WithOwner()
                                .HasForeignKey("BodyMetricId");
                        });

                    b.Navigation("BodyFatPercentage");

                    b.Navigation("Height");

                    b.Navigation("Weight");
                });
#pragma warning restore 612, 618
        }
    }
}
