// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutSessions.Infrastructure.Persistence;

#nullable disable

namespace WorkoutSessions.Infrastructure.Migrations
{
    [DbContext(typeof(WorkoutSessionsDbContext))]
    partial class WorkoutSessionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkoutSessions.Domain.Entity.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkoutProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutProgramId", "Date")
                        .IsUnique();

                    b.ToTable("WorkoutSessions", "workoutsessions");
                });

            modelBuilder.Entity("WorkoutSessions.Domain.Entity.WorkoutSession", b =>
                {
                    b.OwnsMany("WorkoutSessions.Domain.Entity.SessionExercise", "SessionExercises", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("ExerciseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<int>("Reps")
                                .HasColumnType("int");

                            b1.Property<int>("SetNumber")
                                .HasColumnType("int");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<decimal>("Weight")
                                .HasColumnType("decimal(8,2)");

                            b1.Property<Guid>("WorkoutSessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkoutSessionId");

                            b1.ToTable("WorkoutSessionExercises", "workoutsessions");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutSessionId");
                        });

                    b.Navigation("SessionExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
