// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutPrograms.Infrastructure.Persistence;

#nullable disable

namespace WorkoutPrograms.Infrastructure.Migrations
{
    [DbContext(typeof(WorkoutProgramsDbContext))]
    [Migration("20260314222316_Add-UserId-To-WorkoutProgram")]
    partial class AddUserIdToWorkoutProgram
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("IsProcessed", "OccurredOnUtc")
                        .HasFilter("[IsProcessed] = 0");

                    b.ToTable("OutboxMessages", "outbox");
                });

            modelBuilder.Entity("WorkoutPrograms.Domain.Entity.WorkoutProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutPrograms", "workoutprograms");
                });

            modelBuilder.Entity("WorkoutPrograms.Domain.Entity.WorkoutProgram", b =>
                {
                    b.OwnsMany("WorkoutPrograms.Domain.Entity.WorkoutProgramSplit", "Splits", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<int>("Order")
                                .HasColumnType("int");

                            b1.Property<byte[]>("RowVersion")
                                .HasColumnType("varbinary(max)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime?>("UpdatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("WorkoutProgramId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkoutProgramId");

                            b1.ToTable("WorkoutProgramSplits", "workoutprograms");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutProgramId");

                            b1.OwnsMany("WorkoutPrograms.Domain.Entity.WorkoutSplitExercise", "Exercises", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CreatedBy")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<DateTime>("CreatedDate")
                                        .HasColumnType("datetime2");

                                    b2.Property<Guid>("ExerciseId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<bool>("IsActive")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("IsDeleted")
                                        .HasColumnType("bit");

                                    b2.Property<byte[]>("RowVersion")
                                        .HasColumnType("varbinary(max)");

                                    b2.Property<int>("Sets")
                                        .HasColumnType("int");

                                    b2.Property<string>("UpdatedBy")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<DateTime?>("UpdatedDate")
                                        .HasColumnType("datetime2");

                                    b2.Property<Guid>("WorkoutProgramSplitId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("WorkoutProgramSplitId");

                                    b2.ToTable("WorkoutSplitExercises", "workoutprograms");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkoutProgramSplitId");

                                    b2.OwnsOne("WorkoutPrograms.Domain.ValueObjects.RepRange", "RepRange", b3 =>
                                        {
                                            b3.Property<Guid>("WorkoutSplitExerciseId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("Maximum")
                                                .HasColumnType("int")
                                                .HasColumnName("MaximumReps");

                                            b3.Property<int>("Minimum")
                                                .HasColumnType("int")
                                                .HasColumnName("MinimumReps");

                                            b3.HasKey("WorkoutSplitExerciseId");

                                            b3.ToTable("WorkoutSplitExercises", "workoutprograms");

                                            b3.WithOwner()
                                                .HasForeignKey("WorkoutSplitExerciseId");
                                        });

                                    b2.Navigation("RepRange")
                                        .IsRequired();
                                });

                            b1.Navigation("Exercises");
                        });

                    b.Navigation("Splits");
                });
#pragma warning restore 612, 618
        }
    }
}
